modify sequencingLoop in sequencer
SpecularL2/specular pull request #13
Opened 2022-12-11 01:14 UTC by kwhuo68

Core changes:
-Modifies sequencingLoop to use a timer
-Each batch gets added to a batchTxs, and then every timer interval those batches get processed

2022-12-14 07:01 UTC, LEAFERx requested changes

2022-12-14 07:01 UTC, LEAFERx commented on clients/geth/specular/rollup/services/sequencer/sequencer.go
> +			timer.Reset(timeInterval)
Why do you need to reset a ticker?

2022-12-14 07:01 UTC, LEAFERx commented on clients/geth/specular/rollup/services/sequencer/sequencer.go
> +				timer.Reset(timeInterval)
Why you need to reset a ticker?

2022-12-19 05:27 UTC, LEAFERx approved these changes

2022-12-19 08:41 UTC, ujvl approved these changes
couple minor comments but otherwise lgtm!

2022-12-19 08:41 UTC, ujvl commented on clients/geth/specular/rollup/services/sequencer/sequencer.go
> +	for i := 0; i <= len(slice)-1; i++ {
does gofmt enforce no spacing around arithmetic like this, that's annoying

2022-12-19 08:41 UTC, ujvl commented on clients/geth/specular/rollup/services/sequencer/sequencer.go
> +	var timeInterval = 10 * time.Second
nit: define const `TIME_INTERVAL` globally

2022-12-19 08:41 UTC, ujvl commented on clients/geth/specular/rollup/services/sequencer/sequencer.go
> +			combinedBatch = nil
probably makes more sense to just declare `var combinedBatch *rollupTypes.TxBatch` in the case (then it'll also be GC'd automatically w/o assigning nil)

2022-12-20 15:41 UTC, merged