use blocks instead of batches in sequencer
SpecularL2/specular pull request #16
Opened 2022-12-21 05:16 UTC by kwhuo68

Core changes:
-Use blocks instead of batches in sequencer

2022-12-21 05:52 UTC, LEAFERx requested changes

2022-12-21 05:52 UTC, LEAFERx commented on clients/geth/specular/rollup/services/sequencer/sequencer.go
> +		blockCh:              make(chan *types.Blocks, 4096),
`types.Blocks` is a slice, i.e. ref type. you shouldn't use a pointer here

2022-12-24 04:14 UTC, LEAFERx approved these changes

2022-12-24 07:12 UTC, LEAFERx requested changes

2022-12-24 07:12 UTC, LEAFERx commented on clients/geth/specular/rollup/services/sequencer/sequencer.go
> +			batch := rollupTypes.NewTxBatch(*blocks, 0) // TODO: add max batch size
shouldn't create batches here; instead please push these blocks into a local array. create batches in ticks

2022-12-25 04:25 UTC, ujvl approved these changes

2022-12-27 00:29 UTC, merged