read fee params from oracle contract
SpecularL2/specular pull request #246
Opened 2023-11-27 12:39 UTC by siosw

# Goals of PR
- instead of reading the L1 fee scalar / overhead from config, read them from oracle storage slots
- the L1Oracle address is hardcoded in the library, matching Optimisms design

## TODO
- [ ] update fee values in oracle during derivation (in separate PR?)

2023-11-28 19:34 UTC, LEAFERx requested changes
other changes lgtm

2023-11-28 19:34 UTC, LEAFERx commented on lib/el_golang_lib/hook/fee_hook.go
> +	BaseFeeSlot  = common.BigToHash(big.NewInt(253))
can you use the bindings in `ops` to get the slot? the bindings has the storage layout now

2023-12-02 00:53 UTC, LEAFERx approved these changes
lgtm lets wait for geth and magi

2023-12-02 00:53 UTC, LEAFERx commented on lib/el_golang_lib/hook/fee_hook.go
> +	return common.BigToHash(new(big.Int).SetUint64(uint64(baseFeeEntry.Slot))),
one thing im not sure is that why https://github.com/SpecularL2/specular/blob/dc1fac0b07720b8fdbe332a66369074503f86327/ops/bindings/solc/types.go#L81 (comes from optimism). should we change it to string and parse to common.Hex?

2023-12-21 16:48 UTC, ujvl approved these changes

2023-12-21 16:49 UTC, merged