Genesis Generation & Updated Faucet Contract
SpecularL2/specular pull request #43
Opened 2023-02-09 16:11 UTC by destroyersrt

Includes: 
- `createGenesis.js`

Updates:
-  the genesis file based on the `createGenesis.js` file 
- Faucet Contract

2023-02-10 14:25 UTC, ujvl commented on clients/geth/specular/data/genesis.json
> +}
don't check in these changes—otherwise it'll have to be kept in sync w/ calling `create_genesis`

2023-02-10 14:25 UTC, ujvl commented on contracts/scripts/createGenesis.js
> +const genesisPath = "../../clients/geth/specular/data/genesis.json";
we should be able to pass a path in through a flag argument to the script, something like `--in base_genesis.json --out genesis.json`

also: snake case for filename, not camel

2023-02-14 02:59 UTC, aodhgan commented on contracts/src/pre-deploy/Faucet.sol
> +        require(address(this).balance > amountAllowed, "Not enough funds in faucet.");
wont this always pass because `amountAllowed` is not init'ed

2023-02-14 16:16 UTC, ujvl commented on contracts/scripts/createGenesis.js
> +    valueAtSlots[1] = "0x0000000000000000000000000000000000000000000000000de0b6b3a7640000"
what are these values?

2023-02-14 21:21 UTC, ujvl commented on clients/geth/specular/data/genesis.json
>    "gasLimit": "8000000",
nit: name this file `base_genesis.json` to indicate it's a template

2023-02-16 04:51 UTC, LEAFERx requested changes

2023-02-16 04:59 UTC, LEAFERx commented on contracts/scripts/create_genesis.js
> +    valueAtSlots[1] = "0x000000000000000000000000000000000000000000000000002386f26fc10000"
fix in future pr

2023-02-16 05:12 UTC, LEAFERx approved these changes

2023-02-23 21:45 UTC, ujvl approved these changes

2023-02-23 21:55 UTC, merged